[tool.poetry]
name = "pda-abravo-proyecto"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
pandas = "2.1.4"
python = "^3.10"
requests = "^2.32.3"
pytest = "^8.3.2"
logging = "^0.4.9.6"
configparser = "^7.1.0"
pyarrow = "^17.0.0"
fastparquet = "^2024.5.0"
psycopg2-binary = "^2.9.9"
sqlalchemy = "1.4.36"
redshift-connector = "^2.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
